export const COMMON_TEXTS = {
  en: {
    language: "Language",
    theme_light: "Light Mode",
    theme_dark: "Dark Mode",
    expenses: "Expenses",
    budgets: "Budgets",
    goals: "Goals",
    settings: "Settings",
    home: "Home",
    overview: "Overview of your finances",
    track: "Track your daily spending",
    manage: "Manage your budget allocations",
    monitor: "Monitor your saving goals",
  },
  es: {
    language: "Idioma",
    theme_light: "Modo claro",
    theme_dark: "Modo oscuro",
    expenses: "Gastos",
    budgets: "Presupuestos",
    goals: "Metas",
    settings: "Configuración",
    home: "Inicio",
    overview: "Resumen financiero",
    track: "Controla tus gastos diarios",
    manage: "Gestiona tus presupuestos",
    monitor: "Monitorea tus metas de ahorro",
  },
};
